### ISSUE TITLE
encrypted coveralls token

### ISSUE THREAD

**Issue by grooverdan** [ticapix/arduino-toolbox#1]
Just a note coveralls docs suggest/ask/insist on keeping tokens private (though give no guidance on how).

The sercure vars is one way to do it.

http://docs.travis-ci.com/user/environment-variables/

**Comment by ticapix** [comment]
Thanks.
Fixed using Travis env variables

**Comment by grooverdan** [comment]
ah cool. I hadn't got to using those.
